namespaces:
    CommandSchedulerConstraints: TotalCRM\CommandScheduler\Validator\Constraints\

TotalCRM\CommandScheduler\Entity\ScheduledCommand:
    properties:
        cronExpression:
            - NotBlank: ~
            - CommandSchedulerConstraints:CronExpression: { message: "commandScheduler.validation.cron" }
        name:
            - NotBlank: ~
        command:
            - NotBlank: ~
        priority:
            - Type: { type: 'integer'}

